### ISSUE TITLE
Disable scoping

### ISSUE THREAD

**Issue by ascarion** [GetmeUK/ContentFlow#3]
Heja, 

Great work with the ContentFlow. Really makes it easy to provide some pre-defined layouts and elements to my otherwise ignorant users.

In my current use case, I have no need for the feature the local/global scope provides. Is there a way to simply disable this feature, and in particular hide the buttons for it, via configuration?

Thanks and my best.

**Comment by anthonyjb** [comment]
Hi @ascarion sorry I completely missed this issue and it's been such a long time now. We remove the local/global feature sometimes too, there's not dedicated way to do it at the moment I'm afraid so we simply hide the feature in CSS like so:

```css
// This site does not support global snippets

.ct-snippet__tool.ct-snippet__tool--settings {
	right: 46px;	
}

.ct-snippet__tool.ct-snippet__tool--scope {
	display: none !important;	
}

.ct-snippet.ct-snippet--behaviour-pick.ct-snippet--scope-global {
	display: none !important;	
}
```
